import Foundation

// MARK: - In-app help: user guide topics + tool search

public struct HelpTopic: Identifiable, Hashable, Sendable {
    public let id: String
    public let title: String
    public let category: String
    public let keywords: [String]
    public let summary: String
    public let steps: [String]
    /// Where "Show me" takes the user (interpreted by the app), e.g. "deck.present", "right.audio".
    public let target: String?

    public init(_ id: String, _ title: String, category: String, keywords: [String], summary: String, steps: [String], target: String? = nil) {
        self.id = id; self.title = title; self.category = category; self.keywords = keywords
        self.summary = summary; self.steps = steps; self.target = target
    }
}

public enum HelpIndex {
    public static let categories = ["Getting started", "Switching", "Inputs", "Songs & Bible", "Dictionary", "Images",
                                    "AI search", "Audio", "Overlays & scenes", "Automation", "Network", "Outputs & streaming", "Recording", "Presets", "Keyboard & help"]

    static func fold(_ s: String) -> String {
        s.folding(options: [.caseInsensitive, .diacriticInsensitive], locale: nil)
    }
    static func tokens(_ s: String) -> [String] {
        fold(s).components(separatedBy: CharacterSet.alphanumerics.inverted).filter { $0.count > 1 || Int($0) != nil }
    }

    /// Ranked search. Every word of the query must match somewhere in a topic.
    public static func search(_ query: String, in topics: [HelpTopic] = HelpIndex.topics) -> [HelpTopic] {
        let q = fold(query).trimmingCharacters(in: .whitespacesAndNewlines)
        let words = tokens(query)
        guard !words.isEmpty else { return topics }
        var scored: [(Int, Int, HelpTopic)] = []
        for (order, t) in topics.enumerated() {
            let title = fold(t.title), titleWords = tokens(t.title)
            let keys = t.keywords.map(fold), keyWords = t.keywords.flatMap(tokens)
            let summary = fold(t.summary), steps = fold(t.steps.joined(separator: " ")), cat = fold(t.category)
            var score = 0
            if title == q { score += 200 }
            if title.contains(q) { score += 80 }
            if keys.contains(q) { score += 60 }
            var allMatched = true
            for w in words {
                var s = 0
                if titleWords.contains(w) { s += 30 } else if titleWords.contains(where: { $0.hasPrefix(w) }) { s += 18 }
                if keyWords.contains(w) { s += 20 } else if keyWords.contains(where: { $0.hasPrefix(w) }) { s += 10 }
                if cat.contains(w) { s += 6 }
                if summary.contains(w) { s += 5 }
                if steps.contains(w) { s += 2 }
                if s == 0 { allMatched = false; break }
                score += s
            }
            if allMatched { scored.append((score, order, t)) }
        }
        return scored.sorted { $0.0 != $1.0 ? $0.0 > $1.0 : $0.1 < $1.1 }.map { $0.2 }
    }

    public static func topics(in category: String) -> [HelpTopic] { topics.filter { $0.category == category } }

    // MARK: Content

    public static let topics: [HelpTopic] = [
        // Getting started
        HelpTopic("preflight", "Pre-service check", category: "Getting started",
                  keywords: ["checklist", "before service", "ready", "problems", "test", "health", "preflight", "check"],
                  summary: "One click checks inputs, cameras, media files, audio, permissions, disk space, streaming and outputs — with Fix buttons.",
                  steps: ["Press CHECK in the top bar (or ⇧⌘P, or gear menu → Pre-service check…).",
                          "Red items must be fixed before going live; amber items are worth checking; blue are information.",
                          "Use the button on an item to fix it (unmute master, choose a recording folder, open Program Out…), then Check again."]),
        HelpTopic("recovery", "Auto-save and session recovery", category: "Getting started",
                  keywords: ["crash", "autosave", "restore", "recover", "lost", "power cut", "restart"],
                  summary: "Your setup is saved every minute; if LiveDeck closes unexpectedly it offers to restore it.",
                  steps: ["Nothing to set up — inputs, audio, overlays, scenes, looks and output settings are saved automatically.",
                          "After a crash or power cut, a banner at the top offers Restore session.",
                          "For a planned setup you want to reuse every week, save a Preset as well."]),
        HelpTopic("tour", "Tour of the screen", category: "Getting started",
                  keywords: ["overview", "layout", "interface", "start", "beginner", "where"],
                  summary: "LiveDeck has one main page: monitors on top, a lower deck for inputs and content, and a control panel on the right.",
                  steps: ["Top bar: open/save show, Presets, PROGRAM OUT, STREAM, REC, Help (?), computer load and the settings gear.",
                          "PREVIEW (left, green) shows what goes on air next; PROGRAM (right, red) is what is on air now.",
                          "The column between them holds CUT, AUTO, the transition buttons, the T-bar, duration and FTB (fade to black).",
                          "The lower deck has tabs: Inputs, Songs & Bible, Dictionary, AI Search, Media (web search, library, generator), Audio Mixer and Automation.",
                          "The right-hand control panel has tabs: Input, Audio, Overlays, Scenes, Outputs and Presets.",
                          "The bottom status bar shows the format, frame rate, disk space, overlay channels 1–4, Snapshot, Outputs, Multiview and Guides."]),
        HelpTopic("first-service", "Run your first service (quick start)", category: "Getting started",
                  keywords: ["quick start", "church", "sunday", "setup", "how to use", "tutorial", "guide"],
                  summary: "The shortest path from opening the app to being live.",
                  steps: ["Right-click the Inputs area → add your cameras, a video file or a screen capture.",
                          "Open Songs & Bible → Songs → New or Find online; add a Presentation input when asked.",
                          "Click an input's picture to put it on PREVIEW, then press CUT or AUTO to send it to PROGRAM.",
                          "Choose STREAM to add YouTube/Facebook destinations and go live; press REC to record.",
                          "Use PROGRAM OUT to show Program full-screen on the projector or LED screen.",
                          "When everything is set, open Presets → Save current as preset so next week starts in one click."]),
        // Switching
        HelpTopic("cut-auto", "Cut, Auto and transitions", category: "Switching",
                  keywords: ["take", "switch", "fade", "wipe", "slide", "zoom", "mix", "transition"],
                  summary: "Move the Preview picture to Program instantly or with a transition.",
                  steps: ["Put an input on Preview: click its picture, press its PVW button, or press its number key (1–9).",
                          "CUT swaps Preview and Program instantly (key C).",
                          "Pick Fade, Wipe, Slide or Zoom, set Duration, then press AUTO (Return key).",
                          "Double-click an input picture to cut it straight to Program."], target: "deck.inputs"),
        HelpTopic("bus-keys", "Switcher buttons under the monitors", category: "Switching",
                  keywords: ["camera buttons", "switch cameras", "program row", "preview row", "bus", "keys", "cam1", "cam2"],
                  summary: "PROGRAM and PREVIEW rows of illuminated keys let you switch inputs from any tab.",
                  steps: ["They appear under the monitors whenever the Inputs tab is not showing (Songs & Bible, Media, AI Search…).",
                          "PROGRAM row: click to cut that input straight to Program (red). Amber = keyed over Program.",
                          "PREVIEW row: click to put the input on Preview (green). Amber = keyed over Preview.",
                          "CUT and AUTO are on the right. Right-click the strip to show it always or hide it."]),
        HelpTopic("tbar", "T-bar (manual transition)", category: "Switching",
                  keywords: ["t bar", "lever", "manual", "fader"],
                  summary: "Drag the T-bar handle down to perform the transition by hand at your own speed.",
                  steps: ["Put the next input on Preview.", "Drag the T-bar handle from top to bottom; the transition follows your hand.",
                          "Releasing at the bottom completes it; dragging back to the top cancels."]),
        HelpTopic("keys", "Key inputs over Preview and Program", category: "Switching",
                  keywords: ["key", "keyer", "downstream key", "dsk", "overlay input", "k·p", "k·l", "lower third over camera", "preview key"],
                  summary: "Put any input on top of the picture — first on Preview to check it, then live on Program.",
                  steps: ["Every input tile has K·P (key over Preview) and K·L (key over Program, live).",
                          "K·P shows the key only on the Preview monitor; the next CUT or AUTO takes it to Program with the new picture.",
                          "K·L puts it on Program straight away (it fades in). Press again to remove it.",
                          "Songs & Bible and Dictionary have Key PVW / Key PGM buttons; right-click a slide for the same choices.",
                          "Right-click the Preview or Program monitor → Keys to see and clear everything that is keyed.",
                          "For clean keys use a transparent background (slides) or a transparent effect (Generator)."], target: "deck.inputs"),
        HelpTopic("panel-size", "Make the control panel bigger", category: "Getting started",
                  keywords: ["resize", "enlarge", "wider", "panel width", "right panel", "bigger inspector", "half screen", "sidebar"],
                  summary: "The right-hand panel (Input, Audio, Overlays, Scenes, Outputs, Presets) can be narrow, half the window, wide, or any size.",
                  steps: ["Use the PANEL buttons above its tabs: Narrow, Half, Wide or Free.",
                          "In Free, drag the divider between the panel and the monitors to any width.",
                          "Right-click the panel for the same choices. The size is remembered."], target: "right.input"),
        HelpTopic("right-click", "Right-click menus", category: "Getting started",
                  keywords: ["context menu", "right click", "control click", "shortcut menu", "quick actions"],
                  summary: "Almost everything has a right-click menu with the most useful actions.",
                  steps: ["Monitors: CUT/AUTO, transition, choose inputs, keys, overlays, scenes, meter, guides, Program Out, record.",
                          "Input tiles: Preview/Program, keys, mute/solo, controls, adjust, remove.",
                          "Slides and dictionary cards: show, Preview, Program, key on Preview/Program, clear.",
                          "Mixer channels: mute, solo, ON/AFV, effects and presets, reset, Preview/Program.",
                          "Also: top-bar PROGRAM OUT / STREAM / REC, transition column, overlay buttons 1–4, overlay layers, scenes, presets, backgrounds, automation cues.",
                          "On a trackpad: click with two fingers, or Control-click."]),
        HelpTopic("ftb", "Fade to black (FTB)", category: "Switching",
                  keywords: ["black", "blackout", "fade out", "end"],
                  summary: "Fades the whole Program output, including overlays, to black.",
                  steps: ["Press FTB (or key B). Press again to fade back up."]),
        // Inputs
        HelpTopic("add-input", "Add an input (camera, video, image, screen, web page)", category: "Inputs",
                  keywords: ["camera", "video", "file", "image", "photo", "screen", "capture", "web", "url", "source", "new input", "right click"],
                  summary: "Inputs are the sources you switch between. There are 8 empty holders by default.",
                  steps: ["Right-click an empty part of the Inputs area, or press + Add Input.",
                          "Or click the + in an empty holder to fill that exact slot.",
                          "Or drag files from Finder onto the window.",
                          "Cameras include capture cards (Blackmagic, AJA) when their drivers are installed.",
                          "Web Page accepts addresses with or without https://."], target: "deck.inputs"),
        HelpTopic("playlist", "Playlist input (videos, audio, images in one holder)", category: "Inputs",
                  keywords: ["playlist", "walk-in", "loop", "slideshow", "background music", "sequence", "queue", "announcements loop"],
                  summary: "One input that plays a list of videos, songs/audio and images, one after another.",
                  steps: ["Add Input → Playlist. The Input panel shows the Playlist card.",
                          "Drop files or folders on the list, press Add files…, or choose From library (or right-click a Media library item → Add to playlist).",
                          "Set image duration, loop, shuffle, auto-advance and ‘Start playing when taken to Program’.",
                          "Double-click an item to play it now; right-click for cue, duration, move or remove.",
                          "The tile shows ◀ ▶ ▶▶ and the item number; audio goes through the mixer on the playlist's channel.",
                          "Save playlist keeps it for next time; Open saved loads it into any playlist input."], target: "right.input"),
        HelpTopic("zoom", "Show a Zoom meeting", category: "Inputs",
                  keywords: ["zoom", "meeting", "video call", "remote speaker", "teams", "google meet", "window capture", "online guest"],
                  summary: "Join a Zoom meeting and show it as an input with its audio — or receive Zoom's live stream.",
                  steps: ["Add Input → Zoom Meeting / App Window….",
                          "Paste the invite link (or meeting ID + passcode) and press Join in Zoom app.",
                          "When the meeting window appears in the list, press Add as input (tick Meeting audio). Allow Screen & System Audio Recording for LiveDeck when macOS asks.",
                          "Crop the Zoom toolbar in the Input panel, then use Preview/Program or key it like any camera. If Zoom replaces its window, LiveDeck finds it again.",
                          "Hosts can instead use Zoom's Custom Live Streaming: copy the RTMP URL and key from the Zoom window into Zoom (needs ffmpeg).",
                          "To show LiveDeck inside Zoom, share the ‘LiveDeck — Program Out’ window in Zoom."]),
        HelpTopic("stream-input", "Network streams and online videos as inputs", category: "Inputs",
                  keywords: ["hls", "rtmp", "rtsp", "srt", "youtube", "facebook", "twitch", "link", "ffmpeg", "stream input"],
                  summary: "Bring a live stream or an online video in as an input.",
                  steps: ["Add Input → Network Stream (HLS/URL) for .m3u8 links.",
                          "RTMP / RTSP / SRT and YouTube/Twitch/Facebook links need ffmpeg (and yt-dlp for links) installed.",
                          "Right-click the input → Edit address… to change it later."], target: "deck.inputs"),
        HelpTopic("adjust-input", "Zoom, pan, rotate, crop and colour an input", category: "Inputs",
                  keywords: ["geometry", "crop", "brightness", "contrast", "saturation", "rotate", "position", "reset"],
                  summary: "Every input can be framed and colour-corrected in the Input tab of the control panel.",
                  steps: ["Select the input (click its picture) or choose it in Input Channel.",
                          "Drag a slider, or type a number in its value box and press Return.",
                          "The round arrow resets one control; the arrow in a card header resets the whole card; Reset resets everything."], target: "right.input"),
        HelpTopic("playback", "Play, loop and trim video clips", category: "Inputs",
                  keywords: ["play", "pause", "loop", "in point", "out point", "trim", "playlist", "scrub"],
                  summary: "Video and audio files load paused on their first frame.",
                  steps: ["Use the play button on the tile, or the transport in the Input tab.",
                          "Set In / Set Out trims the clip; Clear removes the trim.",
                          "Playlist (Inputs tab) auto-advances Program through clips as each one ends."], target: "right.input"),
        // Songs & Bible
        HelpTopic("songs", "Create, import and edit songs", category: "Songs & Bible",
                  keywords: ["lyrics", "hymn", "worship", "song library", "chorus", "verse", "import", "songselect", "chordpro", "openlyrics", "opensong"],
                  summary: "Songs are typed, pasted, imported or found online, then split into slides automatically.",
                  steps: ["Songs & Bible → Songs → New, then type or paste the words.",
                          "Put Verse 1, Chorus, Bridge… on their own lines; a blank line starts a new slide.",
                          "Import… reads plain text, CCLI SongSelect (.txt/.usr), ChordPro, OpenLyrics and OpenSong files.",
                          "Edits save automatically; the clock icon restores earlier versions; deleted songs go to Trash."], target: "deck.present"),
        HelpTopic("find-lyrics", "Find song lyrics online", category: "Songs & Bible",
                  keywords: ["search lyrics", "internet", "lrclib", "lyrics.ovh", "hymnary", "genius", "musixmatch", "download lyrics"],
                  summary: "Search free lyrics sources, edit the words and save them to the library.",
                  steps: ["Songs & Bible → Songs → Find online.",
                          "Lyrics databases: type the title (and artist) and press Search; pick a result.",
                          "Web sites: choose a site, select the words on the page, press Use selection.",
                          "Edit the words, then Save to Song Library.",
                          "Copyrighted songs need a church licence such as CCLI; public-domain hymns are free."], target: "deck.present"),
        HelpTopic("bible", "Install Bibles and show scripture", category: "Songs & Bible",
                  keywords: ["scripture", "verse", "passage", "translation", "version", "kjv", "niv", "download bible", "search bible"],
                  summary: "Install as many Bible versions as you like and show any passage.",
                  steps: ["English Bibles come with LiveDeck: KJV, ASV, WEB, NET, Geneva, Coverdale, Tyndale and the KJV/ASV Strong's editions (numbers removed for display).",
                          "Songs & Bible → Bible → Get Bibles… to download 1000+ more, or Import file… (JSON, XML, USFM, CSV, .ldbible — a folder or a .zip of them works too). You can also drop them on the Bible area.",
                          "Choose the version and type a reference such as John 3:16-18 or Ps 23, then Go.",
                          "The magnifier searches words in the Bible.",
                          "Click a slide to send it to the Presentation input."], target: "deck.present"),
        HelpTopic("bible-search", "Find scripture fast (search assistant)", category: "Songs & Bible",
                  keywords: ["search bible", "find verse", "autocomplete", "phrase", "word search", "concordance", "which verse says", "suggest"],
                  summary: "Type a reference, a book, a theme or words you remember — suggestions and matching verses appear as you type.",
                  steps: ["Songs & Bible → Bible: start typing in the box (e.g. ‘1 jo’, ‘ps 23’, ‘healing’, ‘the lord is my’).",
                          "Books and references complete instantly; famous passages for the book or theme appear with a ★.",
                          "Words: matching verses are listed best-first with your words highlighted; the phrase is completed for you (‘the lord is my shepherd’).",
                          "Filter by book with the chips, ↑ ↓ to choose, Return to open, Tab to complete, Esc to close. Put words in quotes for an exact phrase.",
                          "Right-click a verse to show it with the next 4 verses or the whole chapter."], target: "deck.present"),
        HelpTopic("go-live-slides", "Put lyrics or scripture on screen", category: "Songs & Bible",
                  keywords: ["presentation input", "live", "next slide", "previous slide", "clicker", "clear", "key", "lower third"],
                  summary: "Slides are shown through a Presentation input that you switch like any other input.",
                  steps: ["Click a slide; it appears on the Presentation input (added automatically if needed).",
                          "Press Preview / Program, or Key over Program to put the words on top of the cameras.",
                          "Next/previous: → / ← on the Songs & Bible tab, or Page Down / Page Up (presentation clickers).",
                          "Clear text removes the words; Hide BG hides the background."], target: "deck.present"),
        HelpTopic("formatting", "Format slides (fonts, position, box, looks)", category: "Songs & Bible",
                  keywords: ["font", "size", "colour", "color", "outline", "shadow", "alignment", "lower third", "look", "theme", "style", "margin"],
                  summary: "The Format column controls exactly how slides look; save your favourite looks.",
                  steps: ["Open Songs & Bible (or Dictionary); Format is the right-hand column.",
                          "Main text, title and reference each have font, size, colour, spacing, outline and shadow.",
                          "Layout chooses the area (full screen, lower third, custom), margins and alignment.",
                          "Text box adds a panel or full-width band behind the words.",
                          "Looks → pick a built-in look; Save look… keeps your own."], target: "deck.present"),
        HelpTopic("backgrounds", "Backgrounds and blend modes for slides", category: "Songs & Bible",
                  keywords: ["background image", "background video", "blend", "blending mode", "multiply", "screen", "overlay", "tint", "opacity", "darken", "gradient"],
                  summary: "Use a colour, gradient, image or looping video behind songs, scripture and dictionary cards — and blend it.",
                  steps: ["Format → Background → Type: Image or Video, then Library… to pick downloaded, generated, imported or shared media (or media already used by an input) — or File… for any file.",
                          "Base under media: pick a colour or gradient.",
                          "Blend mode mixes the media with the base (Multiply tints, Screen lightens, Overlay adds contrast…).",
                          "Media opacity fades the media into the base; Darken background improves readability.",
                          "Media → Web images or Backgrounds library → Use as background puts an image or video straight into the look."], target: "deck.present"),
        HelpTopic("parallel-bible", "Show several Bible versions at once", category: "Songs & Bible",
                  keywords: ["multiple versions", "parallel", "compare translations", "two versions", "side by side", "bilingual", "twi", "french", "stacked"],
                  summary: "Put up to four translations of the same passage on one screen.",
                  steps: ["Songs & Bible → Bible: choose the main version and look up a passage.",
                          "Press Versions and tick up to three more translations.",
                          "Choose Side by side or Stacked; every version shows exactly the same verses and the same text size.",
                          "Format → Content: show or hide version names and set the gap between versions.",
                          "Versions → Show one version only returns to a single translation."], target: "deck.present"),
        // Dictionary
        HelpTopic("dictionary", "Look up a word and show its definition", category: "Dictionary",
                  keywords: ["define", "definition", "meaning", "thesaurus", "synonym", "wikipedia", "wiktionary", "word"],
                  summary: "Search first, preview the card, then send it to Preview, Program or key it.",
                  steps: ["Open the Dictionary tab and choose a dictionary (macOS, English, Wiktionary, Thesaurus, Wikipedia, My Dictionaries).",
                          "Type the word and press Search; pick a result.",
                          "Load into input, then Preview / Program / Key over Program, or add it as an overlay layer.",
                          "Format the card and background in the right-hand column.",
                          "My Dictionaries → Import… adds CSV/TSV/JSON dictionaries (e.g. a Bible dictionary)."], target: "deck.dictionary"),
        // Images
        HelpTopic("image-search", "Search the web for images", category: "Images",
                  keywords: ["picture", "photo", "image search", "openverse", "wikimedia", "web images", "background", "google images"],
                  summary: "Type a word, choose an image, and use it as an input or a slide background.",
                  steps: ["Open Media → Web images, type what you need (e.g. 'sunrise over mountains') and press Search.",
                          "Choose Openverse or Wikimedia Commons; filter by shape (wide suits 16:9 screens).",
                          "Select an image, then Add as input, Preview, Program, or Use as background for slides.",
                          "Web browser mode: right-click an image on a site → Copy Image, then press Paste image.",
                          "The creator and licence are shown — credit them where the licence requires."], target: "deck.images"),
        // Media
        HelpTopic("backgrounds-library", "Free background videos and images", category: "Images",
                  keywords: ["royalty free", "background video", "motion background", "loop", "nasa", "pixabay", "pexels", "starter pack", "download backgrounds", "library"],
                  summary: "Download free backgrounds, keep them in your library and use them anywhere.",
                  steps: ["Media → Backgrounds library. On first launch the starter pack offers NASA public-domain media and generated backgrounds.",
                          "Search online on the right: NASA needs no key; Pixabay and Pexels need a free API key (Get free key).",
                          "Press Get to download; the item appears in your library.",
                          "Select a background → Input, Preview, Program, or Songs & Bible / Dictionary background.",
                          "Right-click for favourites, Show in Finder or Delete; Import adds your own files."], target: "deck.backgrounds"),
        HelpTopic("web-videos", "Search the web for free videos", category: "Images",
                  keywords: ["video search", "stock video", "motion", "clip", "footage", "nasa video", "pixabay", "pexels"],
                  summary: "Find free videos and use them as inputs or slide backgrounds.",
                  steps: ["Media → Web search → Videos.",
                          "Choose NASA (no key), Pixabay or Pexels (free API key), type a word and Search.",
                          "Select a video → Add as input, Preview, Program, or use it as a Songs & Bible / Dictionary background.",
                          "Videos are downloaded into your Media library first, then loop muted as inputs."], target: "deck.images"),
        HelpTopic("local-media", "Add your own images and videos", category: "Images",
                  keywords: ["import", "drag and drop", "drop", "local files", "my pictures", "my videos", "computer", "folder", "upload"],
                  summary: "Bring photos and videos from your Mac into the Media library.",
                  steps: ["Open the Media tab and drag images or videos (or a folder) from Finder onto it — or press Add from computer….",
                          "They are copied into Library → My files.",
                          "Double-click to put one on Preview; right-click for input, Program, slide background, favourites or delete.",
                          "Dropping files anywhere else in the window adds them straight away as inputs."], target: "deck.backgrounds"),
        HelpTopic("generator", "Generate abstract backgrounds and effects", category: "Images",
                  keywords: ["generate", "abstract", "motion", "animated", "particles", "snow", "confetti", "sparkles", "bokeh", "aurora", "light leak", "effect"],
                  summary: "Create moving backgrounds and transparent effects without any files.",
                  steps: ["Media → Generator. Pick a preset or a style, then set colours, speed, amount, size and softness.",
                          "Shuffle gives a new variation of the same style.",
                          "Add as input, Preview or Program; effects (snow, confetti, sparkles, light leak, vignette) are transparent — use Key over Program.",
                          "The KEY / controls buttons on a generator input bring its settings back for live editing.",
                          "Save still or Export seamless loop video adds it to the Backgrounds library for slide backgrounds."], target: "deck.generator"),
        // AI search
        HelpTopic("ai-search", "Ask Claude, ChatGPT, Gemini and other AI", category: "AI search",
                  keywords: ["ai", "artificial intelligence", "claude", "chatgpt", "openai", "gemini", "grok", "deepseek", "mistral", "perplexity", "ollama", "ask", "question", "api key"],
                  summary: "Type a question; the answer becomes formatted slides you can preview, key or put on Program — like the Dictionary.",
                  steps: ["Open the AI Search tab. Choose a provider (Claude, ChatGPT, Gemini, Grok, DeepSeek, Mistral, Perplexity, Groq, Ollama or a custom server).",
                          "Paste your API key once (Get an API key opens the provider's page). Keys stay in the macOS Keychain. Ollama runs on your Mac and needs no key.",
                          "Pick Write as (Answer, Bible study, Sermon points, Prayer points, Announcement…), type the question and press Ask (⌘Return).",
                          "Check the answer — Edit answer lets you correct it; blank lines start new slides.",
                          "Click a slide to show it on the AI Search input, then Preview, Program, Key PVW or Key PGM. Format it in the right-hand column.",
                          "Answers are saved in the list for reuse. AI can be wrong — always check names, dates and scripture."], target: "deck.ai"),
        // Audio
        HelpTopic("mixer", "Audio mixer console", category: "Audio",
                  keywords: ["audio", "sound", "fader", "volume", "gain", "trim", "pan", "mute", "solo", "headphones", "afv", "meter", "levels"],
                  summary: "Each input has a channel strip: input trim, EQ, dynamics, level meters, fader, pan and on/AFV.",
                  steps: ["Open the Audio Mixer tab (or Audio in the control panel).",
                          "Assign an audio device to an input in Input → Audio so its meters move.",
                          "Input knob = trim (drag up/down, double-click to reset); fader = channel level; value boxes accept typed numbers.",
                          "ON keeps the channel in the mix; AFV (audio follows video) only when the input is on Program or keyed; both off = silent.",
                          "Headphones = solo. The red bar above a channel means it is live in the mix.",
                          "Video and audio files and microphones all go through the mixer; the Program mix (after the Master fader) is what is recorded and streamed, in stereo.",
                          "Meters show the real sound level of each channel, left and right."], target: "deck.audio"),
        HelpTopic("audio-effects", "EQ, gate and compressor", category: "Audio",
                  keywords: ["equalizer", "eq", "dynamics", "compressor", "limiter", "noise gate", "hum", "hiss", "de-ess", "voice"],
                  summary: "Clean up and even out a channel's sound.",
                  steps: ["Click a channel's Equalizer or Dynamics display to open its effects.",
                          "Turn the effects On, then pick a preset (Voice clarity, De-hum…) or turn the knobs.",
                          "Watch the curves update; double-click a knob to reset it."], target: "deck.audio"),
        HelpTopic("pan", "Pan (left/right)", category: "Audio",
                  keywords: ["stereo", "left", "right", "balance"],
                  summary: "Place a channel left or right in the stereo mix.",
                  steps: ["Drag the Pan knob; -100 is left, +100 is right, 0 is centre.",
                          "Pan affects the speakers, the recording and the stream, and is recalled with presets."], target: "deck.audio"),
        HelpTopic("monitor", "Hear the mix: monitor level, mics and solo", category: "Audio",
                  keywords: ["speakers", "headphones", "monitor", "feedback", "hear", "no sound", "mute", "silent"],
                  summary: "Control what the Mac's speakers or headphones play without changing the recording.",
                  steps: ["Master strip → MONITOR knob sets the speaker/headphone level.",
                          "Microphones are kept out of the speakers to avoid feedback. Turn on ‘hear mics’ (or gear menu → Hear microphones in the Mac's speakers) to listen to them.",
                          "Headphones button on a channel = solo: only soloed channels play in the speakers; the recording and stream are unchanged.",
                          "MUTE on a channel or the Master silences it everywhere — speakers, recording and stream.",
                          "Online stream inputs (.m3u8 links) play directly and are not controlled by the mixer."], target: "deck.audio"),
        // Overlays & scenes
        HelpTopic("overlays", "Overlays: lower thirds, logos, tickers, clocks", category: "Overlays & scenes",
                  keywords: ["lower third", "logo", "ticker", "scoreboard", "clock", "qr", "picture in picture", "pip", "chroma key", "green screen", "layer"],
                  summary: "Layers sit on top of Program and fade in/out with channels 1–4.",
                  steps: ["Control panel → Overlays → + to add a layer or template.",
                          "Select a layer to edit text, colours, position and scale.",
                          "Toggle it on air with its switch or the 1–4 buttons in the status bar."], target: "right.overlays"),
        HelpTopic("scenes", "Layouts and scenes (multi-camera screens)", category: "Overlays & scenes",
                  keywords: ["layout", "split", "grid", "multi view", "video wall", "side by side", "scene"],
                  summary: "Show several inputs at once in a layout and save it as a scene.",
                  steps: ["Control panel → Scenes → pick a layout.", "Choose which input goes in each slot.", "Save scene to recall it later."], target: "right.scenes"),
        // Automation
        HelpTopic("automation", "Automate lower thirds and keyed inputs", category: "Automation",
                  keywords: ["automate", "timer", "schedule", "cue", "timed", "lower third", "logo", "repeat", "every minutes", "after delay", "time of day"],
                  summary: "Show and hide overlays or keyed inputs by time, by delay, on repeat, or when something happens.",
                  steps: ["Open the Automation tab → Add cue (or pick a ready-made cue).",
                          "What: choose an overlay/lower third, a keyed input or an input, and Show, Hide, Toggle, Cut or Preview.",
                          "When: at a time of day, after a delay, repeat every…, when an input goes on Program, or when recording/streaming starts.",
                          "Hold for N seconds hides it again automatically; ‘Undo when it ends’ follows the camera or recording.",
                          "Press Start automation. Each cue shows a countdown; Run fires a cue now; Activity lists what happened."], target: "deck.automation"),
        // Network
        HelpTopic("network", "Connect several LiveDeck computers", category: "Network",
                  keywords: ["network", "lan", "wifi", "multiple computers", "other mac", "link", "bonjour", "share", "team", "collaborate", "passcode"],
                  summary: "Macs running LiveDeck on the same network find each other, show each other's status, chat and share media.",
                  steps: ["On every computer: Network tab (control panel) → turn on Share on this network, and give the station a name (e.g. Front of house, Stage, Media desk).",
                          "Set the same passcode on all of them if other people use the network. macOS may ask to allow local network access — choose Allow (System Settings → Privacy & Security → Local Network).",
                          "Other computers appear under Stations with a green dot, what is on their Program and Preview, keys and REC/LIVE.",
                          "The LINK button in the top bar shows how many are connected and unread messages."], target: "right.network"),
        HelpTopic("network-chat", "Send messages between computers", category: "Network",
                  keywords: ["chat", "message", "intercom", "talk", "cue", "attention", "standby", "communicate"],
                  summary: "Text messages and quick cues between operators.",
                  steps: ["Network → Messages: choose Everyone or one station, type and Send.",
                          "Quick buttons send Standby, Ready, Go, Next slide, Camera 1/2, Wrap up…",
                          "The ⚠︎ button sends Attention: it flashes amber and beeps on the other computer.",
                          "Incoming messages pop up at the top right; click one to open the Network panel."], target: "right.network"),
        HelpTopic("network-share", "Share media, songs and presets over the network", category: "Network",
                  keywords: ["send file", "share media", "transfer", "copy to other computer", "send song", "send preset", "receive"],
                  summary: "Send library images and videos, input files, songs and presets to another computer — or pull media from theirs.",
                  steps: ["Right-click an item in Media → Library → Send to computer (or … and add as input).",
                          "Right-click a song, a preset or a file/image input → Send to computer.",
                          "Pull: Stations → ⋯ → Browse their media, then Get.",
                          "The receiver accepts in Transfers (or turns on Accept files without asking). Received media goes to Library → Shared; songs to Songs & Bible; presets to Presets."], target: "right.network"),
        // Outputs & streaming
        HelpTopic("program-out", "Full-screen output to a projector or LED wall", category: "Outputs & streaming",
                  keywords: ["projector", "second screen", "display", "led", "fullscreen", "full screen", "hdmi", "program out", "external monitor"],
                  summary: "Show clean Program full screen on a projector, or in a window when you only have one screen.",
                  steps: ["Press PROGRAM OUT. With a second display it opens full screen there; with one screen it opens in a window so your controls stay visible.",
                          "Switch window ↔ full screen: press F or double-click the output, or ⌘⇧F (Output menu), or right-click PROGRAM OUT.",
                          "In full screen, Esc goes back to a window; in a window, Esc closes it.",
                          "Right-click PROGRAM OUT to choose which display, or to close it.",
                          "Outputs tab: turn individual displays on and choose Program or a specific input for each. Outputs on your own screen also open in a window first."], target: "right.outputs"),
        HelpTopic("program-meter", "Audio meter on the Program monitor", category: "Audio",
                  keywords: ["meter", "levels", "vu", "program audio", "loudness"],
                  summary: "A left/right meter on the Program monitor shows the Program mix. It is never drawn on Program Out, recording or stream.",
                  steps: ["Click the bar-chart icon in the Program monitor header to show or hide it.",
                          "Or right-click the Program monitor → Audio meter on this monitor."], target: "deck.audio"),
        HelpTopic("stream", "Stream live to YouTube, Facebook and others", category: "Outputs & streaming",
                  keywords: ["live stream", "youtube", "facebook", "rtmp", "stream key", "simulcast", "go live", "bitrate"],
                  summary: "Send Program (with audio) to one or several platforms at once.",
                  steps: ["Press STREAM, add a destination and paste its server URL and stream key.",
                          "Enable the destinations you want, then Go Live. Every enabled destination streams at once.",
                          "Needs ffmpeg installed; the stream bitrate is separate from the recording bitrate."]),
        HelpTopic("stage-display", "Stage display (confidence monitor)", category: "Outputs & streaming",
                  keywords: ["stage display", "confidence monitor", "preacher screen", "foldback", "timer", "countdown", "message to pastor", "next slide", "singers"],
                  summary: "A screen for the pulpit or the band: clock, current and next slide, REC/LIVE time, a countdown timer and messages from the operator.",
                  steps: ["Control panel → Outputs → Stage display → Open, and choose the display (with one screen it opens in a window).",
                          "Type a message (e.g. ‘5 minutes left’) and press Send; Flash makes it blink; Clear (or ⇧Esc) removes it.",
                          "Set the timer minutes and press Start — it turns orange under 5 minutes and red when over time.",
                          "Choose whether to show the next slide and what is on Program."], target: "right.outputs"),
        HelpTopic("multiview", "Multiview and safe-area guides", category: "Outputs & streaming",
                  keywords: ["multiview", "monitor all", "guides", "safe area", "title safe"],
                  summary: "Monitor every input at once, and check framing.",
                  steps: ["Status bar → Multiview opens a window with all inputs.", "Guides draws the 90% safe area on Program."]),
        // Recording
        HelpTopic("markers", "Chapter markers while recording", category: "Recording",
                  keywords: ["marker", "chapters", "timestamps", "youtube chapters", "edit points", "sermon start"],
                  summary: "Mark moments (worship, sermon, altar call) while recording; a chapters file is saved next to the video.",
                  steps: ["While recording press M, or the MARK button in the status bar, or right-click REC → Add chapter marker.",
                          "Each marker is named after what is on Program. Turn on ‘Add a marker at every cut’ to mark every switch.",
                          "When you stop, LiveDeck saves <recording>.chapters.txt in YouTube chapter format — paste it into the video description."]),
        HelpTopic("record", "Record Program to a file", category: "Recording",
                  keywords: ["record", "recording", "save video", "mp4", "mov", "codec", "hevc", "prores", "snapshot", "folder"],
                  summary: "Record what is on Program with its audio.",
                  steps: ["Press REC (key R); the timer shows the length. Press again to stop.",
                          "Gear menu: resolution, frame rate, codec, container, bitrate and recording folder.",
                          "Snapshot (key S) saves a still image of Program."]),
        // Presets
        HelpTopic("presets", "Save and recall presets", category: "Presets",
                  keywords: ["preset", "save settings", "recall", "load settings", "template", "configuration", "profile", "setup"],
                  summary: "Save the current setup — inputs, audio, overlays, scenes, looks and output settings — and recall it later.",
                  steps: ["Top bar → Presets → Save current as preset… (or the Presets tab in the control panel).",
                          "Name it and tick what to include: inputs, audio mixer, overlays & scenes, output & recording settings, transitions.",
                          "Recall a preset from the Presets menu or tab; Update overwrites it with the current setup.",
                          "Export… / Import… share presets with another Mac.",
                          "Cameras and files come back when the same devices and files are available on this Mac."], target: "right.presets"),
        // Keyboard & help
        HelpTopic("shortcuts", "Keyboard shortcuts", category: "Keyboard & help",
                  keywords: ["hotkeys", "keyboard", "shortcut", "clicker", "assign", "custom keys", "key binding"],
                  summary: "Every main function can have its own shortcut; recommended shortcuts are set up for you. Plain keys never fire while you type.",
                  steps: ["1–9 put inputs on Preview; Return = AUTO; C = CUT; B = FTB; R = record; S = snapshot; L = stream.",
                          "Page Up / Page Down step slides (presentation clickers); ← / → on the Songs & Bible tab.",
                          "⌘K opens Find a tool; ⌘? opens Help.",
                          "Gear menu → Keyboard shortcuts… (⌥⌘/): click a shortcut and press new keys; Delete clears, Esc cancels.",
                          "Smart setup → fill every empty action, reset to recommended, or clear all. Conflicts and macOS shortcuts are flagged.",
                          "Recommended: ⌥1–9 cut input to Program, ⌃1–9 key over Program, ⌘1–7 lower tabs, ⌥⌘1–7 control panel tabs, F1–F4 overlays, ⇧1–5 transition type, P/N playlist, ⌃M master mute."]),
        HelpTopic("help", "Using Help and Find a tool", category: "Keyboard & help",
                  keywords: ["find tool", "search tool", "command", "where is", "how do i"],
                  summary: "Type what you want to do and jump straight to the tool.",
                  steps: ["Press ? in the top bar, ⌘K, or Help → LiveDeck Help.",
                          "Type a few words (e.g. 'blend', 'projector', 'lyrics').",
                          "Choose a result to read the steps; Show me opens the right place in the app."])
    ]
}
